/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    empreendimentos: Empreendimento;
    tipologias: Tipologia;
    'condicoes-comerciais': CondicoesComerciai;
    incorporadoras: Incorporadora;
    media: Media;
    leads: Lead;
    consentimentos: Consentimento;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    empreendimentos: EmpreendimentosSelect<false> | EmpreendimentosSelect<true>;
    tipologias: TipologiasSelect<false> | TipologiasSelect<true>;
    'condicoes-comerciais': CondicoesComerciaisSelect<false> | CondicoesComerciaisSelect<true>;
    incorporadoras: IncorporadorasSelect<false> | IncorporadorasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    consentimentos: ConsentimentosSelect<false> | ConsentimentosSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    parametros: Parametro;
  };
  globalsSelect: {
    parametros: ParametrosSelect<false> | ParametrosSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Um empreendimento só vai ao ar com registro de incorporação e cartório preenchidos. Salve como rascunho até tê-los.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empreendimentos".
 */
export interface Empreendimento {
  id: number;
  nome: string;
  /**
   * Trecho final do endereço da página. Só letras minúsculas e hífens.
   */
  slug: string;
  incorporadora: number | Incorporadora;
  status_obra: 'lancamento' | 'em_obras' | 'entregue';
  /**
   * A data do contrato. A tolerância de 180 dias é explicada na página — não é escondida aqui.
   */
  entrega_prevista?: string | null;
  endereco: {
    logradouro: string;
    numero?: string | null;
    bairro: string;
    cidade: string;
    uf: string;
    cep?: string | null;
  };
  /**
   * Usadas para o mapa e para calcular o entorno.
   */
  geo?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  transporte_proximo?:
    | {
        modo: 'metro' | 'trem' | 'vlt' | 'brt' | 'barca' | 'onibus';
        nome: string;
        /**
         * Tempo real de caminhada, não distância em linha reta.
         */
        minutos_a_pe?: number | null;
        id?: string | null;
      }[]
    | null;
  lazer?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders e fotografias. Prédios entregues valem mais que renders.
   */
  midia?: (number | Media)[] | null;
  /**
   * Obrigatório por lei em qualquer anúncio de unidade em incorporação. Sem estes dois campos o empreendimento não pode ser divulgado.
   */
  registro_legal: {
    registro_incorporacao: string;
    cartorio: string;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incorporadoras".
 */
export interface Incorporadora {
  id: number;
  nome: string;
  /**
   * Endereço onde o comprador acompanha o próprio contrato.
   */
  portal_do_cliente_url?: string | null;
  /**
   * Link de corretor da incorporadora. A análise de crédito é sempre feita lá, nunca aqui.
   */
  link_analise_credito?: string | null;
  autorizacao_publicidade?: {
    concedida_em?: string | null;
    /**
     * A autorização por escrito para divulgar marca, renders e plantas.
     */
    documento?: (number | null) | Media;
    /**
     * Se marcado, cada proposta precisa de aprovação da incorporadora antes de virar link público.
     */
    exige_pre_aprovacao?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva o que a imagem mostra. Aparece para quem usa leitor de tela e quando a imagem não carrega.
   */
  alt: string;
  /**
   * Origem do material, quando houver. Renders e plantas da Cury são publicados sob autorização registrada na incorporadora.
   */
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    ficha?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    planta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologias".
 */
export interface Tipologia {
  id: number;
  /**
   * Como ela chama internamente. Por exemplo "2 quartos com varanda".
   */
  nome: string;
  empreendimento: number | Empreendimento;
  dormitorios: number;
  vagas?: number | null;
  area_privativa: number;
  planta?: (number | Media)[] | null;
  /**
   * Faixa indicativa para a listagem. O valor exato de cada unidade vem da condição comercial, que tem validade.
   */
  faixa_de_preco?: {
    minimo?: number | null;
    maximo?: number | null;
  };
  /**
   * Tetos e rendas das faixas são revistos periodicamente e ficam na configuração do programa, nunca no código.
   */
  faixa_mcmv_elegivel?: ('1' | '2' | '3' | '4')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "condicoes-comerciais".
 */
export interface CondicoesComerciai {
  id: number;
  /**
   * Como a incorporadora nomeia a tabela. Por exemplo "Tabela 12 — agosto".
   */
  referencia: string;
  tipologia: number | Tipologia;
  /**
   * Depois desta data a tabela não pode gerar proposta. A data vem da incorporadora — não é estimada aqui.
   */
  validade_da_tabela: string;
  entrada_percentual?: number | null;
  parcelas_obra?: {
    quantidade?: number | null;
    valor?: number | null;
  };
  baloes?:
    | {
        mes?: number | null;
        valor?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Saldo que vai a repasse na entrega, sujeito a nova análise de crédito naquele momento.
   */
  valor_nas_chaves?: number | null;
  /**
   * Parcelas pagas antes da entrega são corrigidas mensalmente. A parcela de hoje não é a do mês 30.
   */
  indice_reajuste?: ('incc' | 'ipca' | 'igpm') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  nome: string;
  telefone: string;
  mensagem?: string | null;
  /**
   * De onde o lead chegou. Preenchido pelo formulário que o criou.
   */
  origem?: string | null;
  /**
   * Movido à mão por ela na medida em que a conversa avança.
   */
  estagio?: ('novo' | 'em_conversa' | 'aguardando_retomada' | 'convertido' | 'perdido') | null;
  /**
   * Data escolhida por ela quando marca o lead como "aguardando retomada". O formulário público nunca preenche este campo.
   */
  retomar_em?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consentimentos".
 */
export interface Consentimento {
  id: number;
  lead: number | Lead;
  /**
   * O que ela pode usar este contato para fazer, em texto claro.
   */
  finalidade: string;
  /**
   * Qual versão da cópia de consentimento a pessoa aceitou.
   */
  texto_versao: string;
  /**
   * Lido do cabeçalho da requisição no servidor, nunca enviado pelo cliente.
   */
  ip?: string | null;
  /**
   * Preenchido à mão quando ela é avisada para parar de usar este contato.
   */
  revogado_em?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'empreendimentos';
        value: number | Empreendimento;
      } | null)
    | ({
        relationTo: 'tipologias';
        value: number | Tipologia;
      } | null)
    | ({
        relationTo: 'condicoes-comerciais';
        value: number | CondicoesComerciai;
      } | null)
    | ({
        relationTo: 'incorporadoras';
        value: number | Incorporadora;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'consentimentos';
        value: number | Consentimento;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empreendimentos_select".
 */
export interface EmpreendimentosSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  incorporadora?: T;
  status_obra?: T;
  entrega_prevista?: T;
  endereco?:
    | T
    | {
        logradouro?: T;
        numero?: T;
        bairro?: T;
        cidade?: T;
        uf?: T;
        cep?: T;
      };
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  transporte_proximo?:
    | T
    | {
        modo?: T;
        nome?: T;
        minutos_a_pe?: T;
        id?: T;
      };
  lazer?:
    | T
    | {
        item?: T;
        id?: T;
      };
  midia?: T;
  registro_legal?:
    | T
    | {
        registro_incorporacao?: T;
        cartorio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologias_select".
 */
export interface TipologiasSelect<T extends boolean = true> {
  nome?: T;
  empreendimento?: T;
  dormitorios?: T;
  vagas?: T;
  area_privativa?: T;
  planta?: T;
  faixa_de_preco?:
    | T
    | {
        minimo?: T;
        maximo?: T;
      };
  faixa_mcmv_elegivel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "condicoes-comerciais_select".
 */
export interface CondicoesComerciaisSelect<T extends boolean = true> {
  referencia?: T;
  tipologia?: T;
  validade_da_tabela?: T;
  entrada_percentual?: T;
  parcelas_obra?:
    | T
    | {
        quantidade?: T;
        valor?: T;
      };
  baloes?:
    | T
    | {
        mes?: T;
        valor?: T;
        id?: T;
      };
  valor_nas_chaves?: T;
  indice_reajuste?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incorporadoras_select".
 */
export interface IncorporadorasSelect<T extends boolean = true> {
  nome?: T;
  portal_do_cliente_url?: T;
  link_analise_credito?: T;
  autorizacao_publicidade?:
    | T
    | {
        concedida_em?: T;
        documento?: T;
        exige_pre_aprovacao?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        ficha?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        planta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  nome?: T;
  telefone?: T;
  mensagem?: T;
  origem?: T;
  estagio?: T;
  retomar_em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consentimentos_select".
 */
export interface ConsentimentosSelect<T extends boolean = true> {
  lead?: T;
  finalidade?: T;
  texto_versao?: T;
  ip?: T;
  revogado_em?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Índices e regras que mudam com o tempo. Toda página que mostra um número daqui mostra também a data desta revisão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametros".
 */
export interface Parametro {
  id: number;
  incc?: {
    /**
     * Acumulado de 12 meses do INCC, em porcentagem. Enquanto estiver vazio, nenhuma parcela é exibida no site — nem a de hoje, porque as duas só aparecem juntas.
     */
    taxa_anual?: number | null;
    /**
     * Quando este número foi conferido na fonte. Aparece ao lado de cada valor.
     */
    data_revisao?: string | null;
    fonte?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametros_select".
 */
export interface ParametrosSelect<T extends boolean = true> {
  incc?:
    | T
    | {
        taxa_anual?: T;
        data_revisao?: T;
        fonte?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}